import React from 'react';
import { useTranslation } from 'react-i18next';

/**
 * Provenance marking: where a number or statement comes from (operator request
 * 2026-09-30: "visual markings to know when the AI generates data that is based
 * on the human inputs and the ones generated").
 *
 * ONE small set of kinds, used everywhere:
 *   protocol    Human - the agronomist protocol (read-only, authoritative)
 *   operator    Human - entered / edited by the farm team in SenseHub
 *   measured    sensors and meters
 *   calculated  SenseHub maths and assumptions (1:150 design dilution, bands,
 *               EC-scaled targets, EC estimates ...)
 *   ai          AI-generated (dashed outline: an opinion, not a fact)
 *
 * Every kind has its own icon + colour token (--prov-*) + label, so colour is
 * never the only cue. Strings: common:provenance.*.
 *
 *   <ProvenanceBadge kind="protocol" />                 chip: icon + label
 *   <ProvenanceBadge kind="calculated" from="protocol"/> "Calculated from protocol"
 *   <ProvenanceMark kind="operator" detail="…" />       icon-only inline marker
 *   <BasisChips basis={['protocol','measured']} />      what an AI item rests on
 *   <ProvenanceLegend />                                collapsible key
 */

export const PROVENANCE_KINDS = ['protocol', 'operator', 'measured', 'calculated', 'ai'];

/** Fertilizer advisor `basis` values (backend fertilizerAdviceFormat.BASIS) → provenance kind. */
export const BASIS_KIND = {
  protocol: 'protocol',
  operator_targets: 'operator',
  operator_notes: 'operator',
  measured: 'measured',
  senseHub_calculation: 'calculated',
  ai_general_knowledge: 'ai',
};
export const BASIS_VALUES = Object.keys(BASIS_KIND);

/** Known basis values of an item, in the fixed order; [] when absent (older advices). */
export function cleanBasis(basis) {
  if (!Array.isArray(basis)) return [];
  const set = new Set(basis);
  return BASIS_VALUES.filter(b => set.has(b));
}

/** True when an AI item rests only on the AI's own general knowledge (not on the farm's data). */
export const isAiOnlyBasis = (basis) => {
  const b = cleanBasis(basis);
  return b.length > 0 && b.every(x => x === 'ai_general_knowledge');
};

// Literal class names (Tailwind JIT) per kind.
const STYLE = {
  protocol: { text: 'text-prov-protocol', chip: 'border-prov-protocol/50 bg-prov-protocol/10' },
  operator: { text: 'text-prov-operator', chip: 'border-prov-operator/50 bg-prov-operator/10' },
  measured: { text: 'text-prov-measured', chip: 'border-prov-measured/50 bg-prov-measured/10' },
  calculated: { text: 'text-prov-calculated', chip: 'border-prov-calculated/50 bg-prov-calculated/10' },
  ai: { text: 'text-prov-ai', chip: 'border-prov-ai/60 bg-prov-ai/10 border-dashed' },
};
const kindOf = (k) => (PROVENANCE_KINDS.includes(k) ? k : 'calculated');

const PATHS = {
  // document with a folded corner and text lines: the written protocol
  protocol: (
    <>
      <path d="M4 1.75h5.25L12.5 5v9.25H4z" />
      <path d="M9 1.75V5.25h3.5M6.25 8h4M6.25 10.5h4M6.25 13h2.5" />
    </>
  ),
  // a person: entered by the farm team
  operator: (
    <>
      <circle cx="8" cy="5" r="2.75" />
      <path d="M2.75 14.5c.5-3 2.6-4.75 5.25-4.75s4.75 1.75 5.25 4.75" />
    </>
  ),
  // a gauge with a needle: read from a sensor / meter
  measured: (
    <>
      <path d="M2 11.5a6 6 0 1 1 12 0" />
      <path d="M8 11.5l3-4.25" />
      <circle cx="8" cy="11.5" r="1" fill="currentColor" />
      <path d="M2 14.25h12" />
    </>
  ),
  // a calculator: worked out by SenseHub
  calculated: (
    <>
      <rect x="3" y="1.75" width="10" height="12.5" rx="1.5" />
      <path d="M5.25 4.5h5.5M5.5 8h.01M8 8h.01M10.5 8h.01M5.5 11h.01M8 11h.01M10.5 11h.01" strokeWidth="2" />
    </>
  ),
  // sparkles: generated by the AI
  ai: (
    <>
      <path d="M6.5 2l1.1 3.4L11 6.5 7.6 7.6 6.5 11 5.4 7.6 2 6.5l3.4-1.1z" fill="currentColor" fillOpacity=".25" />
      <path d="M12 9.5l.6 1.9 1.9.6-1.9.6-.6 1.9-.6-1.9-1.9-.6 1.9-.6z" fill="currentColor" />
    </>
  ),
};

/** The kind's icon (decorative; the label or aria-label carries the meaning). */
export function ProvenanceIcon({ kind, className = '' }) {
  const k = kindOf(kind);
  return (
    <svg viewBox="0 0 16 16" width="12" height="12" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"
      aria-hidden="true" focusable="false" className={`shrink-0 ${className}`.trim()} data-provenance-icon={k}>
      {PATHS[k]}
    </svg>
  );
}

function useLabels() {
  const { t } = useTranslation('common');
  return {
    t,
    label: (kind, from) => (from ? t(`provenance.from.${kindOf(kind)}.${kindOf(from)}`, { defaultValue: t(`provenance.kind.${kindOf(kind)}`) }) : t(`provenance.kind.${kindOf(kind)}`)),
    desc: (kind) => t(`provenance.desc.${kindOf(kind)}`),
  };
}

/**
 * Chip: icon (+ the source icon for a derived value) + label. `detail` is the
 * tooltip (default: the kind's description). `emphasis` = stronger fill (used for
 * "AI knowledge - not from your data").
 */
export function ProvenanceBadge({ kind, from = null, label = null, detail = null, emphasis = false, className = '', ...rest }) {
  const { label: lbl, desc } = useLabels();
  const k = kindOf(kind);
  const s = STYLE[k];
  const text = label ?? lbl(k, from);
  return (
    <span
      className={`inline-flex items-center gap-1 rounded border px-1.5 py-0.5 text-[11px] leading-4 font-semibold normal-case tracking-normal whitespace-nowrap align-middle ${s.text} ${s.chip} ${emphasis ? '!bg-prov-ai/20 border-2' : ''} ${className}`.trim()}
      data-provenance={k}
      {...(from ? { 'data-provenance-from': kindOf(from) } : {})}
      title={detail || desc(k)}
      {...rest}
    >
      <ProvenanceIcon kind={k} />
      {from && <ProvenanceIcon kind={from} className={`-ms-0.5 ${STYLE[kindOf(from)].text}`} />}
      <span>{text}</span>
    </span>
  );
}

/**
 * Icon-only inline marker for a single value (table cells). Screen readers get
 * the label + detail; sighted users the icon, colour and tooltip.
 */
export function ProvenanceMark({ kind, from = null, detail = null, className = '', ...rest }) {
  const { label: lbl, desc } = useLabels();
  const k = kindOf(kind);
  const text = lbl(k, from);
  const tip = detail ? `${text}: ${detail}` : `${text}: ${desc(k)}`;
  return (
    <span role="img" aria-label={tip} title={tip} data-provenance={k} {...(from ? { 'data-provenance-from': kindOf(from) } : {})}
      className={`inline-flex items-center align-middle ${STYLE[k].text} ${className}`.trim()} {...rest}>
      <ProvenanceIcon kind={k} />
      {from && <ProvenanceIcon kind={from} className={`-ms-0.5 ${STYLE[kindOf(from)].text}`} />}
    </span>
  );
}

/**
 * What an AI item is based on. `compact` = icons only (dense lists).
 * - no basis (advices before 2026-09-30): "Basis not recorded"
 * - only ai_general_knowledge: one emphasised chip "AI knowledge - not from your data"
 * - else: "Based on" + one chip per basis value
 */
export function BasisChips({ basis, compact = false, className = '' }) {
  const { t } = useLabels();
  const b = cleanBasis(basis);
  if (b.length === 0) {
    return (
      <span className={`inline-flex items-center gap-1 text-[11px] text-muted italic ${className}`.trim()} data-basis="none">
        <ProvenanceMark kind="ai" />{t('provenance.basis.notRecorded')}
      </span>
    );
  }
  if (isAiOnlyBasis(b)) {
    return <ProvenanceBadge kind="ai" emphasis label={t('provenance.basis.aiOnly')} detail={t('provenance.basis.aiOnlyHint')} className={className} data-basis="ai_only" />;
  }
  const label = t('provenance.basis.label');
  if (compact) {
    return (
      <span className={`inline-flex items-center gap-0.5 ${className}`.trim()} data-basis={b.join(' ')}>
        {b.map(x => <ProvenanceMark key={x} kind={BASIS_KIND[x]} detail={`${label}: ${t(`provenance.basis.${x}`)}`} />)}
      </span>
    );
  }
  return (
    <span className={`inline-flex flex-wrap items-center gap-1 ${className}`.trim()} data-basis={b.join(' ')}>
      <span className="text-[11px] text-muted">{label}:</span>
      {b.map(x => <ProvenanceBadge key={x} kind={BASIS_KIND[x]} label={t(`provenance.basis.${x}`)} />)}
    </span>
  );
}

/**
 * Collapsible key of the markings. The summary shows every icon, so the key is
 * useful even closed. `showBasis` adds the note on AI "based on" chips.
 */
export function ProvenanceLegend({ kinds = PROVENANCE_KINDS, showBasis = true, defaultOpen = false, className = '', ...rest }) {
  const { t, desc } = useLabels();
  return (
    <details className={`group rounded-card border border-line bg-panel px-3 py-2 text-sm ${className}`.trim()} open={defaultOpen || undefined} data-testid="provenance-legend" {...rest}>
      <summary className="flex cursor-pointer select-none flex-wrap items-center gap-x-2 gap-y-1 min-h-[28px]">
        <span className="font-semibold text-ink">{t('provenance.legend.title')}</span>
        <span className="inline-flex flex-wrap items-center gap-1.5" aria-hidden="true">
          {kinds.map(k => <span key={k} className={STYLE[kindOf(k)].text}><ProvenanceIcon kind={k} /></span>)}
        </span>
        <span className="text-xs text-muted group-open:hidden">{t('provenance.legend.show')}</span>
      </summary>
      <dl className="mt-2 grid grid-cols-1 sm:grid-cols-[auto_1fr] gap-x-3 gap-y-1.5">
        {kinds.map(k => (
          <React.Fragment key={k}>
            <dt><ProvenanceBadge kind={k} /></dt>
            <dd className="text-xs text-muted min-w-0 mb-1 sm:mb-0">{desc(k)}</dd>
          </React.Fragment>
        ))}
      </dl>
      {showBasis && (
        <div className="mt-2 pt-2 border-t border-line text-xs text-muted space-y-1">
          <p>{t('provenance.legend.basisNote')}</p>
          <p className="flex flex-wrap items-center gap-1.5">
            <BasisChips basis={['protocol', 'measured']} />
            <BasisChips basis={['ai_general_knowledge']} />
          </p>
          <p>{t('provenance.legend.derivedNote')}</p>
        </div>
      )}
    </details>
  );
}

export default ProvenanceBadge;
